using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ChatApp.Shared.Protocol.Tcp.Binary.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class TcpBinaryCodecGenerator : IIncrementalGenerator
{
    private const string ContractAttributeName =
        "ChatApp.Shared.Protocol.Tcp.Binary.Generation.TcpBinaryContractAttribute";
    private const string FieldAttributeName =
        "ChatApp.Shared.Protocol.Tcp.Binary.Generation.TcpBinaryFieldAttribute";

    private static readonly DiagnosticDescriptor InvalidDescriptor = new(
        "CTB001",
        "Invalid binary descriptor",
        "Descriptor '{0}' must be a non-generic top-level static partial class",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidContract = new(
        "CTB002",
        "Unsupported binary contract",
        "Contract '{0}' must be a non-generic, non-inherited, non-abstract class with an accessible parameterless constructor",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidFieldNumber = new(
        "CTB003",
        "Invalid binary field number",
        "Field number '{0}' on descriptor '{1}' must be unique and between 1 and 536870911",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidProperty = new(
        "CTB004",
        "Invalid binary contract property",
        "Property '{0}' on contract '{1}' must exist and expose public get and set/init accessors",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedPropertyType = new(
        "CTB005",
        "Unsupported binary contract property type",
        "Property '{0}' has unsupported tagged binary type '{1}'",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingFields = new(
        "CTB006",
        "Binary descriptor has no fields",
        "Descriptor '{0}' must declare at least one TcpBinaryField attribute",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor MissingRequiredField = new(
        "CTB007",
        "Required property is not described",
        "Required property '{0}' on contract '{1}' must have an explicit stable field number",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor RequiredNullableField = new(
        "CTB008",
        "Required nullable property is not representable",
        "Required property '{0}' on contract '{1}' cannot be nullable because tagged v1 represents null by field absence",
        "ChatApp.BinaryGenerator",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private const string AttributeSource = """
        // <auto-generated />
        #nullable enable
        namespace ChatApp.Shared.Protocol.Tcp.Binary.Generation
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
            internal sealed class TcpBinaryContractAttribute : global::System.Attribute
            {
                public TcpBinaryContractAttribute(global::System.Type contractType) => ContractType = contractType;
                public global::System.Type ContractType { get; }
            }

            [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
            internal sealed class TcpBinaryFieldAttribute : global::System.Attribute
            {
                public TcpBinaryFieldAttribute(int fieldNumber, string propertyName)
                {
                    FieldNumber = fieldNumber;
                    PropertyName = propertyName;
                }

                public int FieldNumber { get; }
                public string PropertyName { get; }
            }
        }
        """;

    private static readonly SymbolDisplayFormat FullyQualifiedNullableFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions
            | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
            | SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource(
                "TcpBinaryDescriptorAttributes.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<INamedTypeSymbol> descriptors = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                ContractAttributeName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        context.RegisterSourceOutput(descriptors, static (output, descriptor) =>
            Generate(output, descriptor));
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol descriptor)
    {
        Location location = descriptor.Locations.FirstOrDefault() ?? Location.None;
        if (!IsValidDescriptor(descriptor))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                InvalidDescriptor,
                location,
                descriptor.ToDisplayString()));
            return;
        }

        AttributeData? contractAttribute = descriptor.GetAttributes()
            .FirstOrDefault(static attribute =>
                attribute.AttributeClass?.ToDisplayString() == ContractAttributeName);
        if (contractAttribute?.ConstructorArguments.Length != 1
            || contractAttribute.ConstructorArguments[0].Value is not INamedTypeSymbol contract
            || !IsValidContract(contract))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                InvalidContract,
                location,
                contractAttribute?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? "<missing>"));
            return;
        }

        ImmutableArray<AttributeData> fieldAttributes = descriptor.GetAttributes()
            .Where(static attribute => attribute.AttributeClass?.ToDisplayString() == FieldAttributeName)
            .ToImmutableArray();
        if (fieldAttributes.IsDefaultOrEmpty)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                MissingFields,
                location,
                descriptor.ToDisplayString()));
            return;
        }

        var usedNumbers = new HashSet<int>();
        var usedProperties = new HashSet<string>(StringComparer.Ordinal);
        var fields = new List<FieldModel>(fieldAttributes.Length);
        var hasError = false;

        foreach (AttributeData attribute in fieldAttributes)
        {
            int number = attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is int fieldNumber
                    ? fieldNumber
                    : 0;
            string propertyName = attribute.ConstructorArguments.Length > 1
                ? attribute.ConstructorArguments[1].Value as string ?? string.Empty
                : string.Empty;
            Location attributeLocation = attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation() ?? location;

            if (number <= 0
                || number > 0x1FFF_FFFF
                || !usedNumbers.Add(number)
                || !usedProperties.Add(propertyName))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidFieldNumber,
                    attributeLocation,
                    number,
                    descriptor.ToDisplayString()));
                hasError = true;
                continue;
            }

            IPropertySymbol? property = contract.GetMembers(propertyName)
                .OfType<IPropertySymbol>()
                .FirstOrDefault(static candidate => !candidate.IsStatic);
            if (property is null
                || property.IsIndexer
                || property.GetMethod?.DeclaredAccessibility != Accessibility.Public
                || property.SetMethod?.DeclaredAccessibility != Accessibility.Public)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidProperty,
                    attributeLocation,
                    propertyName,
                    contract.ToDisplayString()));
                hasError = true;
                continue;
            }

            if (!TryClassify(property.Type, out TypeModel type))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    UnsupportedPropertyType,
                    attributeLocation,
                    propertyName,
                    property.Type.ToDisplayString()));
                hasError = true;
                continue;
            }

            if (property.IsRequired && type.IsNullable)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    RequiredNullableField,
                    attributeLocation,
                    propertyName,
                    contract.ToDisplayString()));
                hasError = true;
                continue;
            }

            fields.Add(new FieldModel(number, property, type));
        }

        foreach (IPropertySymbol requiredProperty in contract.GetMembers()
                     .OfType<IPropertySymbol>()
                     .Where(static property => property.IsRequired && !property.IsStatic))
        {
            if (!usedProperties.Contains(requiredProperty.Name))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    MissingRequiredField,
                    location,
                    requiredProperty.Name,
                    contract.ToDisplayString()));
                hasError = true;
            }
        }

        if (hasError)
        {
            return;
        }

        fields.Sort(static (left, right) => left.Number.CompareTo(right.Number));
        string source = Render(descriptor, contract, fields);
        string hintName = GetCollisionFreeHintName(descriptor);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static bool IsValidDescriptor(INamedTypeSymbol descriptor)
    {
        if (!descriptor.IsStatic
            || descriptor.ContainingType is not null
            || descriptor.Arity != 0
            || descriptor.IsFileLocal)
        {
            return false;
        }

        return descriptor.DeclaringSyntaxReferences
            .Select(static reference => reference.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(static declaration => declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private static bool IsValidContract(INamedTypeSymbol contract)
    {
        if (contract.TypeKind != TypeKind.Class
            || contract.IsAbstract
            || contract.IsStatic
            || contract.IsGenericType
            || contract.IsUnboundGenericType
            || contract.IsFileLocal
            || contract.BaseType?.SpecialType != SpecialType.System_Object)
        {
            return false;
        }

        return contract.InstanceConstructors.Any(constructor =>
            constructor.Parameters.Length == 0
            && constructor.DeclaredAccessibility == Accessibility.Public);
    }

    private static string GetCollisionFreeHintName(INamedTypeSymbol descriptor)
    {
        // Four hex digits per UTF-16 code unit makes this mapping reversible. In particular,
        // namespaces such as A.B_C and A_B.C cannot collapse to the same AddSource hint name.
        string identity = descriptor.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var builder = new StringBuilder(identity.Length * 4 + 24);
        builder.Append("TcpBinaryCodec_");
        foreach (char current in identity)
        {
            builder.Append(((int)current).ToString("X4", CultureInfo.InvariantCulture));
        }

        return builder.Append(".g.cs").ToString();
    }

    private static bool TryClassify(ITypeSymbol sourceType, out TypeModel model)
    {
        bool nullable = sourceType.NullableAnnotation == NullableAnnotation.Annotated;
        ITypeSymbol type = sourceType;
        if (sourceType is INamedTypeSymbol named
            && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
        {
            nullable = true;
            type = named.TypeArguments[0];
        }

        if (type.TypeKind == TypeKind.Enum && type is INamedTypeSymbol enumType)
        {
            if (!TryClassify(enumType.EnumUnderlyingType!, out TypeModel underlying)
                || underlying.Kind is TypeKindModel.String or TypeKindModel.Bytes
                or TypeKindModel.Single or TypeKindModel.Double or TypeKindModel.Boolean)
            {
                model = default;
                return false;
            }

            model = new TypeModel(TypeKindModel.Enum, nullable, underlying.Kind);
            return true;
        }

        TypeKindModel kind = type.SpecialType switch
        {
            SpecialType.System_Boolean => TypeKindModel.Boolean,
            SpecialType.System_SByte => TypeKindModel.SByte,
            SpecialType.System_Byte => TypeKindModel.Byte,
            SpecialType.System_Int16 => TypeKindModel.Int16,
            SpecialType.System_UInt16 => TypeKindModel.UInt16,
            SpecialType.System_Int32 => TypeKindModel.Int32,
            SpecialType.System_UInt32 => TypeKindModel.UInt32,
            SpecialType.System_Int64 => TypeKindModel.Int64,
            SpecialType.System_UInt64 => TypeKindModel.UInt64,
            SpecialType.System_Single => TypeKindModel.Single,
            SpecialType.System_Double => TypeKindModel.Double,
            SpecialType.System_String => TypeKindModel.String,
            _ => TypeKindModel.Unsupported
        };

        if (kind == TypeKindModel.Unsupported
            && type is IArrayTypeSymbol { Rank: 1, ElementType.SpecialType: SpecialType.System_Byte })
        {
            kind = TypeKindModel.Bytes;
        }

        model = new TypeModel(kind, nullable, TypeKindModel.Unsupported);
        return kind != TypeKindModel.Unsupported;
    }

    private static string Render(
        INamedTypeSymbol descriptor,
        INamedTypeSymbol contract,
        IReadOnlyList<FieldModel> fields)
    {
        var builder = new StringBuilder(8_192);
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        if (!descriptor.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ")
                .Append(descriptor.ContainingNamespace.ToDisplayString())
                .AppendLine(";")
                .AppendLine();
        }

        string accessibility = descriptor.DeclaredAccessibility == Accessibility.Public
            ? "public"
            : "internal";
        string targetType = contract.ToDisplayString(FullyQualifiedNullableFormat);
        builder.Append(accessibility).Append(" static partial class ")
            .Append(EscapeIdentifier(descriptor.Name)).AppendLine()
            .AppendLine("{")
            .Append("    public static global::ChatApp.Shared.Protocol.Tcp.Binary.ITcpBinaryCodec<")
            .Append(targetType).AppendLine("> Codec { get; } = new GeneratedCodec();")
            .AppendLine()
            .Append("    private sealed class GeneratedCodec : global::ChatApp.Shared.Protocol.Tcp.Binary.ITcpBinaryCodec<")
            .Append(targetType).AppendLine(">")
            .AppendLine("    {")
            .AppendLine("        public void Encode(")
            .AppendLine("            global::System.Buffers.IBufferWriter<byte> destination,")
            .Append("            ").Append(targetType).AppendLine(" value,")
            .AppendLine("            global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryLimits limits)")
            .AppendLine("        {")
            .AppendLine("            global::System.ArgumentNullException.ThrowIfNull(destination);")
            .AppendLine("            global::System.ArgumentNullException.ThrowIfNull(value);")
            .AppendLine("            var writer = new global::ChatApp.Shared.Protocol.Tcp.Binary.TaggedBinaryWriter(destination, limits);");

        for (var index = 0; index < fields.Count; index++)
        {
            RenderWrite(builder, fields[index], index);
        }

        builder.AppendLine("        }")
            .AppendLine()
            .AppendLine("        public bool TryDecode(")
            .AppendLine("            in global::System.Buffers.ReadOnlySequence<byte> payload,")
            .AppendLine("            global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryLimits limits,")
            .Append("            out ").Append(targetType).AppendLine("? value,")
            .AppendLine("            out global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryDecodeError error)")
            .AppendLine("        {")
            .AppendLine("            value = default;")
            .AppendLine("            var reader = new global::ChatApp.Shared.Protocol.Tcp.Binary.TaggedBinaryReader(payload, limits);");

        for (var index = 0; index < fields.Count; index++)
        {
            FieldModel field = fields[index];
            builder.Append("            ")
                .Append(field.Property.Type.ToDisplayString(FullyQualifiedNullableFormat))
                .Append(" field").Append(index).Append(" = ")
                .Append(GetDefaultExpression(field)).AppendLine(";");
            builder.Append("            bool seen").Append(index).AppendLine(" = false;");
        }

        builder.AppendLine("            while (reader.TryReadFieldHeader(out var fieldNumber, out var wireType))")
            .AppendLine("            {")
            .AppendLine("                switch (fieldNumber)")
            .AppendLine("                {");

        for (var index = 0; index < fields.Count; index++)
        {
            RenderReadCase(builder, fields[index], index);
        }

        builder.AppendLine("                    default:")
            .AppendLine("                        if (!reader.TrySkip(wireType))")
            .AppendLine("                        {")
            .AppendLine("                            error = reader.Error;")
            .AppendLine("                            return false;")
            .AppendLine("                        }")
            .AppendLine("                        break;")
            .AppendLine("                }")
            .AppendLine("            }")
            .AppendLine()
            .AppendLine("            if (reader.Error != global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryDecodeError.None)")
            .AppendLine("            {")
            .AppendLine("                error = reader.Error;")
            .AppendLine("                return false;")
            .AppendLine("            }")
            .AppendLine();

        for (var index = 0; index < fields.Count; index++)
        {
            if (!fields[index].Property.IsRequired)
            {
                continue;
            }

            builder.Append("            if (!seen").Append(index).AppendLine(")")
                .AppendLine("            {")
                .AppendLine("                error = global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryDecodeError.MissingRequiredField;")
                .AppendLine("                return false;")
                .AppendLine("            }")
                .AppendLine();
        }

        builder
            .Append("            value = new ").Append(targetType).AppendLine()
            .AppendLine("            {");

        for (var index = 0; index < fields.Count; index++)
        {
            builder.Append("                ")
                .Append(EscapeIdentifier(fields[index].Property.Name))
                .Append(" = field").Append(index).AppendLine(",");
        }

        builder.AppendLine("            };")
            .AppendLine("            error = global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryDecodeError.None;")
            .AppendLine("            return true;")
            .AppendLine("        }")
            .AppendLine("    }")
            .AppendLine("}");
        return builder.ToString();
    }

    private static void RenderWrite(StringBuilder builder, FieldModel field, int index)
    {
        string property = "value." + EscapeIdentifier(field.Property.Name);
        string expression = field.Type.IsNullable ? "fieldValue" + index : property;
        if (field.Type.IsNullable)
        {
            builder.Append("            if (").Append(property)
                .Append(" is { } fieldValue").Append(index).AppendLine(")")
                .AppendLine("            {");
        }

        builder.Append(field.Type.IsNullable ? "                " : "            ")
            .Append("writer.").Append(GetWriteMethod(field.Type)).Append('(')
            .Append(field.Number.ToString(CultureInfo.InvariantCulture)).Append(", ")
            .Append(GetWriteValueExpression(field.Type, expression)).AppendLine(");");

        if (field.Type.IsNullable)
        {
            builder.AppendLine("            }");
        }
    }

    private static void RenderReadCase(StringBuilder builder, FieldModel field, int index)
    {
        builder.Append("                    case ")
            .Append(field.Number.ToString(CultureInfo.InvariantCulture)).AppendLine(":")
            .AppendLine("                    {")
            .Append("                        if (seen").Append(index).AppendLine(")")
            .AppendLine("                        {")
            .AppendLine("                            error = global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryDecodeError.DuplicateField;")
            .AppendLine("                            return false;")
            .AppendLine("                        }")
            .Append("                        seen").Append(index).AppendLine(" = true;");

        TypeKindModel kind = field.Type.Kind == TypeKindModel.Enum
            ? field.Type.EnumUnderlyingKind
            : field.Type.Kind;
        string readMethod = GetReadMethod(kind);
        string decodedName = "decoded" + index;
        builder.Append("                        if (!reader.").Append(readMethod)
            .Append("(wireType, out var ").Append(decodedName).AppendLine("))")
            .AppendLine("                        {")
            .AppendLine("                            error = reader.Error;")
            .AppendLine("                            return false;")
            .AppendLine("                        }");

        string? rangeCondition = GetRangeCondition(kind, decodedName);
        if (rangeCondition is not null)
        {
            builder.Append("                        if (").Append(rangeCondition).AppendLine(")")
                .AppendLine("                        {")
                .AppendLine("                            error = global::ChatApp.Shared.Protocol.Tcp.Binary.TcpBinaryDecodeError.ValueOutOfRange;")
                .AppendLine("                            return false;")
                .AppendLine("                        }");
        }

        builder.Append("                        field").Append(index).Append(" = ")
            .Append(GetReadValueExpression(field, decodedName)).AppendLine(";")
            .AppendLine("                        break;")
            .AppendLine("                    }");
    }

    private static string GetWriteMethod(TypeModel type)
    {
        TypeKindModel kind = type.Kind == TypeKindModel.Enum ? type.EnumUnderlyingKind : type.Kind;
        return kind switch
        {
            TypeKindModel.Boolean => "WriteBool",
            TypeKindModel.SByte or TypeKindModel.Int16 or TypeKindModel.Int32 => "WriteInt32",
            TypeKindModel.Byte or TypeKindModel.UInt16 or TypeKindModel.UInt32 => "WriteUInt32",
            TypeKindModel.Int64 => "WriteInt64",
            TypeKindModel.UInt64 => "WriteUInt64",
            TypeKindModel.Single => "WriteSingle",
            TypeKindModel.Double => "WriteDouble",
            TypeKindModel.String => "WriteString",
            TypeKindModel.Bytes => "WriteBytes",
            _ => throw new InvalidOperationException("Unsupported generated write kind.")
        };
    }

    private static string GetReadMethod(TypeKindModel kind) => kind switch
    {
        TypeKindModel.Boolean => "TryReadBool",
        TypeKindModel.SByte or TypeKindModel.Int16 or TypeKindModel.Int32 => "TryReadInt32",
        TypeKindModel.Byte or TypeKindModel.UInt16 or TypeKindModel.UInt32 => "TryReadUInt32",
        TypeKindModel.Int64 => "TryReadInt64",
        TypeKindModel.UInt64 => "TryReadUInt64",
        TypeKindModel.Single => "TryReadSingle",
        TypeKindModel.Double => "TryReadDouble",
        TypeKindModel.String => "TryReadString",
        TypeKindModel.Bytes => "TryReadBytes",
        _ => throw new InvalidOperationException("Unsupported generated read kind.")
    };

    private static string GetWriteValueExpression(TypeModel type, string expression)
    {
        if (type.Kind != TypeKindModel.Enum)
        {
            return type.Kind == TypeKindModel.Bytes
                ? "global::System.MemoryExtensions.AsSpan(" + expression + ")"
                : expression;
        }

        return "(" + GetSpecialTypeName(type.EnumUnderlyingKind) + ")" + expression;
    }

    private static string GetReadValueExpression(FieldModel field, string decodedName)
    {
        string value = field.Type.Kind switch
        {
            TypeKindModel.Enum => "(" + field.Property.Type.ToDisplayString(FullyQualifiedNullableFormat)
                                  .TrimEnd('?') + ")" + decodedName,
            TypeKindModel.SByte => "(sbyte)" + decodedName,
            TypeKindModel.Byte => "(byte)" + decodedName,
            TypeKindModel.Int16 => "(short)" + decodedName,
            TypeKindModel.UInt16 => "(ushort)" + decodedName,
            TypeKindModel.String or TypeKindModel.Bytes when !field.Type.IsNullable => decodedName + "!",
            _ => decodedName
        };
        return value;
    }

    private static string? GetRangeCondition(TypeKindModel kind, string value) => kind switch
    {
        TypeKindModel.SByte => value + " < sbyte.MinValue || " + value + " > sbyte.MaxValue",
        TypeKindModel.Byte => value + " > byte.MaxValue",
        TypeKindModel.Int16 => value + " < short.MinValue || " + value + " > short.MaxValue",
        TypeKindModel.UInt16 => value + " > ushort.MaxValue",
        _ => null
    };

    private static string GetDefaultExpression(FieldModel field)
    {
        if (field.Type.IsNullable)
        {
            return "default";
        }

        return field.Type.Kind switch
        {
            TypeKindModel.String => "string.Empty",
            TypeKindModel.Bytes => "global::System.Array.Empty<byte>()",
            _ => "default"
        };
    }

    private static string GetSpecialTypeName(TypeKindModel kind) => kind switch
    {
        TypeKindModel.SByte => "sbyte",
        TypeKindModel.Byte => "byte",
        TypeKindModel.Int16 => "short",
        TypeKindModel.UInt16 => "ushort",
        TypeKindModel.Int32 => "int",
        TypeKindModel.UInt32 => "uint",
        TypeKindModel.Int64 => "long",
        TypeKindModel.UInt64 => "ulong",
        _ => throw new InvalidOperationException("Unsupported enum underlying type.")
    };

    private static string EscapeIdentifier(string identifier) => "@" + identifier;

    private sealed class FieldModel
    {
        public FieldModel(int number, IPropertySymbol property, TypeModel type)
        {
            Number = number;
            Property = property;
            Type = type;
        }

        public int Number { get; }
        public IPropertySymbol Property { get; }
        public TypeModel Type { get; }
    }

    private readonly struct TypeModel
    {
        public TypeModel(TypeKindModel kind, bool isNullable, TypeKindModel enumUnderlyingKind)
        {
            Kind = kind;
            IsNullable = isNullable;
            EnumUnderlyingKind = enumUnderlyingKind;
        }

        public TypeKindModel Kind { get; }
        public bool IsNullable { get; }
        public TypeKindModel EnumUnderlyingKind { get; }
    }

    private enum TypeKindModel : byte
    {
        Unsupported,
        Boolean,
        SByte,
        Byte,
        Int16,
        UInt16,
        Int32,
        UInt32,
        Int64,
        UInt64,
        Single,
        Double,
        String,
        Bytes,
        Enum
    }
}
